[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "7NBN3gJgmoe2x9un3KKH7yeEvV3TSrDavvQ9SN8VvQ3D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
