[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dev_capital = "5MHA6ForrBUbPbom2x231cNsMCQvE4VCpQ7F6rKMt8bS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
