[package]
name = "getprograms"
version = "0.1.0"
edition = "2021"
author = "bergabman"

[dependencies]
solana-sdk = "1.17.14"
solana-client = "1.17.14"
solana-account-decoder = "1.17.14"
tokio = { version = "^1.35.1", features = ["full"] }
anyhow = "1.0.79"
futures = "0.3.30"