[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "5CGXgvPRVtW81njC68V46DKzoXFoysteMezTS67JL4iL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
